apiVersion: v1
kind: Pod
metadata:
  name: nginx
  labels:
    env: test
spec:
  containers:
  - name: nginx
    image: nginx
    imagePullPolicy: IfNotPresent
  nodeSelector:
    accelerator: blue
  tolerations:
  - key: "colour"
    operator: "Equal"
    value: "blue"
    effect: "NoSchedule"