{{- if .Values.VolumeExists.disabled -}}
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: task-pv-claim
spec:
  persistentVolumeReclaimPolicy: Retain
  storageClassName: longhorn
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 3Gi
{{- end }}
