apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ .Values.persistence.claimName }}
  annotations:
    {{- if .Values.skipuninstall }}
    "helm.sh/resource-policy": keep
    {{- end }}
spec:
  storageClassName: {{ .Values.persistence.storageClassName }}
  accessModes:
    {{- toYaml .Values.persistence.accessModes | nindent 12 }}
  resources:
    requests:
      storage: {{ .Values.persistence.storage }}
