apiVersion: v1
kind: PersistentVolume
metadata:
  name: {{ .Values.persistence.volumeName }}
spec:
  storageClassName: {{ .Values.persistence.storageClassName }}
  capacity:
    storage: {{ .Values.persistence.storage }}
  accessModes:
    {{- .Values.persistence.accessModes | nindent 8 }}
  hostPath:
    path: {{ ".Values.volumeMounts.mountPath" }}